spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/gestionstock?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Zoyim6415@@
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy : ANT_PATH_MATCHER

## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        ejb:
          interceptor: org.sid.gestiondestock.interceptor.Interceptor
#Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8081

flickr:
  apiKey: 2b5dcea977f2dba53ccf13fc93bc31a8
  apiSecret: 1a0d90d77dbd4e6f
  appKey: 72157720863317214-3eb93380ce336fb9
  appSecret: 5e4e336b94167d9d
